soot-infoflow-summaries/src/soot/jimple/infoflow/methodSummary/data/provider/EagerSummaryProvider.java
soot-infoflow-summaries/src/soot/jimple/infoflow/methodSummary/data/provider/XMLSummaryProvider.java
soot-infoflow-summaries/src/soot/jimple/infoflow/methodSummary/taintWrappers/TaintWrapperFactory.java
soot-infoflow-summaries/summariesManual/java.io.ObjectInputStream$GetField.xml
soot-infoflow-summaries/summariesManual/org.apache.http.RequestLine.xml
soot-infoflow-summaries/test/soot/jimple/infoflow/test/methodSummary/junit/SummaryTaintWrapperTests.java

Adding an eager summary provider and load all manual summaries during testing

Adding an eager summary provider

---

soot-infoflow-android/src/soot/jimple/infoflow/android/resources/controls/EditTextControl.java

Fixing cases where FlowDroid detects sensitive fields, which are not actually password fields

Fixing cases where FlowDroid detects sensitive fields

---

.gitignore
soot-infoflow-android/src/soot/jimple/infoflow/android/source/AndroidSourceSinkManager.java
soot-infoflow/src/soot/jimple/infoflow/results/xml/InfoflowResultsSerializer.java
soot-infoflow/src/soot/jimple/infoflow/results/xml/XmlConstants.java
soot-infoflow/src/soot/jimple/infoflow/rifl/RIFLParser.java
soot-infoflow/src/soot/jimple/infoflow/rifl/RIFLSourceSinkDefinitionProvider.java
soot-infoflow/src/soot/jimple/infoflow/util/SootMethodRepresentationParser.java

Fix parsing RIFL file by:
1-Handle input XML elements.
2-Handle no return type in the method signature.
And serialize category of source and sinks data leaks into the XML output file

Fix parsing RIFL file and serialize category into the XML output file

---

soot-infoflow-android/src/soot/jimple/infoflow/android/resources/ARSCFileParser.java

The new ArrayResource was missing a getter for the list elements

ArrayResource: getter getArrayElements() created

---

soot-infoflow/src/soot/jimple/infoflow/rifl/RIFLSourceSinkDefinitionProvider.java

Before this commit, the last parsed category from RIFL file only returning when calling `getHumanReadableDescription` that used to serialize the category to the output file or `getID`.
Now, returning the right parsed categories.

Hot fix, returning the right category from getHumanReadableDescription and getID in RIFL way

---

soot-infoflow/pom.xml
soot-infoflow/test/soot/jimple/infoflow/test/securibench/supportClasses/DummyHttpRequest.java
soot-infoflow/test/soot/jimple/infoflow/test/securibench/supportClasses/DummyHttpResponse.java
soot-infoflow/test/soot/jimple/infoflow/test/securibench/supportClasses/DummyServletContext.java

This PR prepares the info-flow pom for deployment to Maven Central
* add pom.xml information: developer, repository, link to github
* change dependency versions to releases (as required by Maven Central)
* get rid of self-created "j2ee.jar" in bin folder

Prepare pom.xml for Deployment to Maven Central

---

soot-infoflow/src/soot/jimple/infoflow/codeOptimization/DeadCodeEliminator.java
soot-infoflow/src/soot/jimple/infoflow/codeOptimization/InterproceduralConstantValuePropagator.java

Without this fix, FlowDroid removes callsites from methods during deadcode elimination but does not remove the corresponding callgraph edges. This leads to errors in analyses that process callsites which are stored as sources of callgraph edges.

Fix missing removal of callgraph edges for removed callsites in deadcode elimination

---

soot-infoflow-android/src/soot/jimple/infoflow/android/entryPointCreators/AbstractAndroidEntryPointCreator.java
soot-infoflow-android/src/soot/jimple/infoflow/android/entryPointCreators/AndroidEntryPointCreator.java
soot-infoflow-android/src/soot/jimple/infoflow/android/entryPointCreators/components/AbstractComponentEntryPointCreator.java
soot-infoflow-android/src/soot/jimple/infoflow/android/entryPointCreators/components/ActivityEntryPointCreator.java
soot-infoflow-android/src/soot/jimple/infoflow/android/entryPointCreators/components/BroadcastReceiverEntryPointCreator.java
soot-infoflow-android/src/soot/jimple/infoflow/android/entryPointCreators/components/ContentProviderEntryPointCreator.java
soot-infoflow-android/src/soot/jimple/infoflow/android/entryPointCreators/components/FragmentEntryPointCreator.java
soot-infoflow-android/src/soot/jimple/infoflow/android/entryPointCreators/components/ServiceConnectionEntryPointCreator.java
soot-infoflow-android/src/soot/jimple/infoflow/android/entryPointCreators/components/ServiceEntryPointCreator.java
soot-infoflow-android/src/soot/jimple/infoflow/android/manifest/ProcessManifest.java

The commit 2ec4cb2185f3707de9481eb2df8379b2097b7f66 did not solve the whole problem of #171. Indeed, while a false system component is now able to be represented in Flowdroid, its lifecycle cannot due to the same problem. This solution fixes the ad-hoc problem but I have seen 23 other similar checks in the code. I can impact other issues for false system classes.

Fix: The life-cycle of false system classes was not built in their dummyMainMethod (related to #171)

---

soot-infoflow-android/src/soot/jimple/infoflow/android/SetupApplication.java
soot-infoflow-android/src/soot/jimple/infoflow/android/entryPointCreators/AbstractAndroidEntryPointCreator.java
soot-infoflow-android/src/soot/jimple/infoflow/android/manifest/ProcessManifest.java
soot-infoflow/src/soot/jimple/infoflow/util/SystemClassHandler.java

Actually, 2ec4cb2185f3707de9481eb2df8379b2097b7f66 and 89d4a3008592fb718a6a25c2ce1eba3b72d0dc6a did not fix the whole problem. Although it fixed #171, I found that the problem for #175 is the same, so I come with this more generic solution. It will avoid futur serial problems with the same issue as the test to know if a class is a system one is made more than 60 times in the entire code.
PS : In 89d4a3008592fb718a6a25c2ce1eba3b72d0dc6a I did move the manifest object in parent classes. It is not needed anymore for the moment but I did not remove it from the code as it may be useful in the futur. I don't know if you want to leave it or not, just let me know.

Fix: generic way for testing if a class should be taken into account as a component

---

soot-infoflow-android/src/soot/jimple/infoflow/android/entryPointCreators/AndroidEntryPointConstants.java
soot-infoflow-android/src/soot/jimple/infoflow/android/entryPointCreators/AndroidEntryPointUtils.java

Some apps use the com.google.android.maps.MapActivity (deprecated) super class to create activities. And even if they are declared in the AndroidManifest, in createDummyMainInternal method of AndroidEntryPointCreator class they would not be recognized as a component because the componentType would be "Plain" and not Activity. Therefore the component would not appear in the dummyMainMethod leading to a non-analyzed component. This PR fixes the problem.

Add: com.google.android.maps.MapActivity entrypoint as Activity

---

soot-infoflow-android/src/soot/jimple/infoflow/android/callbacks/AbstractCallbackAnalyzer.java

Flowdroid does register callback methods of implemented interfaces of callbacks present in AndroidCallbacks.txt but does not take into account such callbacks being **classes** and not interfaces like android.telephony.PhoneStatelistener.
This fixes the problem.

Fix: register callback methods of extended classes

---

soot-infoflow-android/src/soot/jimple/infoflow/android/SetupApplication.java
soot-infoflow-android/src/soot/jimple/infoflow/android/config/XMLConfigurationParser.java
soot-infoflow-android/src/soot/jimple/infoflow/android/config/XMLConstants.java
soot-infoflow-cmd/schema/FlowDroidConfiguration.xsd
soot-infoflow-cmd/src/soot/jimple/infoflow/cmd/MainClass.java
soot-infoflow/src/soot/jimple/infoflow/InfoflowConfiguration.java
soot-infoflow/src/soot/jimple/infoflow/results/xml/InfoflowResultsSerializer.java
soot-infoflow/src/soot/jimple/infoflow/results/xml/XmlConstants.java

Added two commandline options and config options. One for outputting linenumbers in XML result files and another one to use original variable names if available. (Partially related to issue #76: https://github.com/secure-software-engineering/FlowDroid/issues/76)

Added commandline options (Partially related to issue #76)

---

soot-infoflow-android/src/soot/jimple/infoflow/android/iccta/IccRedirectionCreator.java

With IccTA enabled to detect ICC flows, when to instrument ```onServiceConnected(ComponentName, IBinder)``` for bound Service, a ```Local``` of ```NullType``` is created to represent the first argument of type ```ComponentName```. However, ```NullType``` is not acceptable in the final Jimple code generated by Soot, when validating the body. Thus, an exception with the following message will be thrown:
> (<dummyMainClass: void redirector0(android.content.ServiceConnection,android.content.Intent)>) local type not allowed in final code: null_type local
This simple fix replaces ```NullType``` with the correct type ```ComponentName```. Though even with this fix, FlowDroid still lacks the mechanism to detect ICC flows of bound Service, this fix can at least make sure FlowDroid finish its …

Fix "local type not allowed in final code: null_type" exception

---

soot-infoflow-android/src/soot/jimple/infoflow/android/callbacks/AbstractCallbackAnalyzer.java
soot-infoflow-android/src/soot/jimple/infoflow/android/config/SootConfigForAndroid.java

For the case where customized activity extends from `androidx.appcompat.app.AppCompatActivity`, the invocation of the method `setContentView` is used to find the corresponding layout XML file and the method `invokesSetContentView` is used to judge the invocation of `setContentView`.  However, `invokesSetContentView` treated the situation that one of the superclass except than `android.app.Activity`, `android.support.v7.app.ActionBarActivity` and `android.support.v7.app.AppCompatActivity` with declaring of method `setContentView` as no invocation of `setContentView`. Since overriding method in the subclass is common such as it did in `androidx.appcompat.app.AppCompatActivity`, this is obviously incorrect and caused the skip of layout file analysis and lead to the missing of layout-resided …

Fixed callbacks in layout XML did not add to call graph bug

---

soot-infoflow-android/src/soot/jimple/infoflow/android/iccta/IccRedirectionCreator.java

The current implementation of IccTA assumes ICC methods contain at least one parameter, which is an Intent. However, there are ICC methods without parameter. For example for methods in class `PendingIntent`, as the base object is already severed as an intent, a parameter of Intent is not necessary. IccTA cannot handle these methods and throws one of the following exceptions, depending on how Soot implements `getArg()` in different versions:
- For Soot version 4.0.0 included in FlowDroid's `pom.xml`, `NullPointerException` is thrown at the statement with `getArg()`.
- For the nightly-built version of Soot, `IllegalArgumentException` with message "value may not be null" is thrown at line 441 of `IccRedirectionCreator.java`.
Though when I checked ICC methods collected by IC3, I only found …

Fix exceptions thrown when handling ICC methods with no parameter

---

soot-infoflow-android/src/soot/jimple/infoflow/android/entryPointCreators/components/AbstractComponentEntryPointCreator.java
soot-infoflow-android/src/soot/jimple/infoflow/android/entryPointCreators/components/ActivityEntryPointCreator.java
soot-infoflow-android/src/soot/jimple/infoflow/android/entryPointCreators/components/BroadcastReceiverEntryPointCreator.java
soot-infoflow-android/src/soot/jimple/infoflow/android/entryPointCreators/components/ServiceEntryPointCreator.java

Different to FlowDroid v2.0, the logic of IccTA is changed, which leads to the current version fails to handle ICC targeted BroadcastReceivers and IntentServices. Specifically, it fails to handle `onReceive(Context, Intent)` of BroadcastReceivers  and `onHandleIntent(Intent)` of IntentServices in the following DroidBench or ICC-Bench benchmark apps:
- [BroadcastTaintAndLeak1](https://github.com/secure-software-engineering/DroidBench/tree/master/eclipse-project/InterComponentCommunication/BroadcastTaintAndLeak1)
- [icc_dynregister1](https://github.com/fgwei/ICC-Bench/tree/master/icc_dynregister1)
- [icc_dynregister2](https://github.com/fgwei/ICC-Bench/tree/master/icc_dynregister2)
- [icc_intentservice](https://github.com/fgwei/ICC-Bench/tree/master/icc_intentservice)
I thus adapted the …

Fix ICC for BroadcastReceivers and IntentServices

---

soot-infoflow-android/src/soot/jimple/infoflow/android/resources/ARSCFileParser.java

When loading the resources of an [android-platforms](https://github.com/Sable/android-platforms) android.jar the assertion on non-null extra bytes triggers in `readConfigTable`.
For example for API 26 I am getting extra bytes 0x100000000000000 and 0x200000000000000 multiple times.
In a regular program this is no problem as assertions are usually not enabled however in unit tests assertions are enabled by default and therefore all unit tests fail that need to load resources from an android-platform android.jar.

readConfigTable fails in unit test because of assertion

---

soot-infoflow-summaries/summariesManual/java.lang.Integer.xml
soot-infoflow-summaries/summariesManual/java.lang.Long.xml

Hello,
I noticed an error in the signatures of `parseInt` and `parseLong`. It caused the taint flow to not correctly propagate across these functions.
Let me know if I am wrong.
Thanks,
Luca

Fixed parseInt and parseLong method signatures in summaries

---

soot-infoflow-android/pom.xml

when I run the test of droidBench in soot-infoflow-android module, the test result cannot be displayed normally, and the following error message is displayed:
**SLF4J: Failed to load class “org.slf4j.impl.StaticLoggerBinder”**
so I add two dependency int pom.xml, and the result can be displayed normally.

The running result of droidBench in soot-infoflow-android module cannot be displayed normally.

---

README.MD

This adds a warning that the tests do not run on JDK versions newer than 8, as discussed in #305.

Add tests warning to README

---

soot-infoflow-android/src/soot/jimple/infoflow/android/resources/ARSCFileParser.java

The resource type is required for regenerating the XML of certain attributes e.g. in layouts

Save resType for complex resources

---

soot-infoflow-android/src/soot/jimple/infoflow/android/manifest/IManifestHandler.java

The current heuristic to compare package name of component classes again hard-coded list is less effective when dealing with malware apps (see https://github.com/secure-software-engineering/FlowDroid/issues/240 and https://github.com/secure-software-engineering/FlowDroid/issues/171). I understand this is for the sake of performance. However, if there is no entry point can be detected according to the current heuristic, one can assume that the app is likely to be malware with system-like package name.  All enabled components should be added to the list of entry point classes. For such cases, I think it is better to analyze all than nothing.

add heristic for malware

---

soot-infoflow/src/soot/jimple/infoflow/problems/rules/SourcePropagationRule.java

Referring to c204cfaf6fb48e9b54eb81f9d2b1cad6aa8e2d5c "do not skip source methods if our source definition is on a callback or the return value", the condition should be inverted.

Fix typo in SourcePropagationRule.java

---

soot-infoflow-android/src/soot/jimple/infoflow/android/source/parsers/xml/XMLSourceSinkParser.java

The current endElement in XMLSourceSinkParser for FIELD_TAG does not clear all old data as METHOD_TAG when field definition finished, which will pollute the next definition. Fix it to properly clear all.
For example:
```xml
<field signature="&lt;A: D E&gt;">
<accessPath isSource="true" isSink="false" />
</field>
<method signature="&lt;A: B C()&gt;">
<return>
<accessPath isSource="true" isSink="false" />
</return>
</method>
```
The next definition will be polluted as source.

Properly clear data after field definition
